# Generated by Django 4.0.3 on 2022-03-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('ST', 'Starting')], default='OUT', max_length=3),
        ),
    ]
