# Generated by Django 4.0.3 on 2022-03-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_forecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='category',
        ),
    ]
