# Generated by Django 4.0.3 on 2022-03-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_forecast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='associated_forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.forecast'),
        ),
    ]
