# Generated by Django 4.0.3 on 2022-03-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_associated_forecast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'balance', 'verbose_name_plural': 'balances'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'verbose_name': 'forecast', 'verbose_name_plural': 'forecasts'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transaction'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('ST', 'Starting')], default='OUT', max_length=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('ST', 'Starting')], max_length=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
